---
title: "Examen final Modules 4 et 5"
author: "Olivier Rué - Valentin Loux"
subtitle: "DUBii 2021"
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: resources/biblio.bib 
csl: resources/biomed-central.csl
output:
    html_document:
      css: [css/style.css, 'https://use.fontawesome.com/releases/v5.0.9/css/all.css']
      self_contained: true
      number_sections: false
      code_folding: "hide"
      toc: true
      toc_depth: 3
      toc_float: true
      includes:
        after_body: resources/footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=FALSE, echo =TRUE, cache = FALSE, message = FALSE, warning = FALSE, cache.lazy = FALSE,
                      fig.height = 3.5, fig.width = 10.5)
```

# Consignes {-}

Complétez ce document en remplissant les chunks vides pour écrire le code qui vous a permis de répondre à la question. Les réponses attendant un résultat chiffré ou une explication devront être insérés entre le balises html `code`. Par exemple pour répondre à la question suivante :

    La bioinfo c'est : <code>MERVEILLEUX</code>.
    
N'hésitez pas à commenter votre code, enrichier le rapport en y insérant des résultats ou des graphiques/images pour expliquer votre démarche. N'oubliez pas les **bonnes pratiques** pour une recherche **reproductible** !
Nous souhaitons à minima que l'analyse soit reproductible sur le cluster de l'IFB.

# Introduction {-}

Vous allez travailler sur des données de reséquençage d'un génome bactérien : _Bacillus subtilis_. Les données sont issues de cet article :

* [Complete Genome Sequences of 13 Bacillus subtilis Soil Isolates for Studying Secondary Metabolite Diversity](https://mra.asm.org/content/9/2/e01406-19)

# Analyses

## Organisation de votre espace de travail

```{bash}
# Je travaille dans mon répertoire de travail qui est associé au projet "dubii2021" sur le cluster de l'IFB.
cd /shared/projects/dubii2021/glelandais/modules-4-5-evaluation/.
# Création de répertoires pour organiser les fichiers.
mkdir raw-data
mkdir quality-controls
mkdir clean-data
mkdir mapping
```

## Téléchargement des données brutes

Récupérez les fichiers FASTQ issus du run **SRR10390685** grâce à l'outil <strong class="tool">sra-tools</strong> @sratoolkit

```{bash}
cd raw-data
# Comme je vais utiliser les outils en dehors d'un script,
# il me semble que cette commande est importante.
salloc --cpus-per-task=10 --mem=1G
# Chargement du module
module load sra-tools
# Lancement du téléchargement
srun fasterq-dump -p --split-files SRR10390685
# Deux fichiers FASTQ ont été obtenus
```

Combien de reads sont présents dans les fichiers R1 et R2 ?

```{bash}
# Le nombre de reads est égal au nombre de lignes divisé 
# par 4 (un read comporte 4 lignes)
grep -c "^@" SRR10390685_1.fastq
grep -c "^@" SRR10390685_2.fastq
```

Les fichiers FASTQ contiennent <code>7066055</code> reads.

Téléchargez le génome de référence de la souche ASM904v1 de _Bacillus subtilis_ disponible à [cette adresse](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/GCF_000009045.1_ASM904v1_genomic.fna.gz)

```{bash}
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/GCF_000009045.1_ASM904v1_genomic.fna.gz
```

Quelle est la taille de ce génome ?

```{bash}
# Décompression du féichier génome
gunzip GCF_000009045.1_ASM904v1_genomic.fna.gz
# Décompte du nombre de base
cat GCF_000009045.1_ASM904v1_genomic.fna | grep -v "NC_" | tr --delete "\n" | wc -c

# Note : J'ai trouvé de l'aide ici :
# https://dridk.me/genome_chiffre_1.html
```

La taille de ce génome est de <code>4215606</code> paires de bases.

Téléchargez l'annotation de la souche ASM904v1 de _Bacillus subtilis_ disponible à [cette adresse](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/GCF_000009045.1_ASM904v1_genomic.gff.gz)

```{bash}
# Téléchargement
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/GCF_000009045.1_ASM904v1_genomic.gff.gz
# Décompression du fichier
gunzip GCF_000009045.1_ASM904v1_genomic.gff.gz
```

Combien de gènes sont connus pour ce génome ?

```{bash}
# Récupération de la troisième colonne du fichier et
# dénombrement des occurences de gene
cut -f 3 GCF_000009045.1_ASM904v1_genomic.gff | grep -c gene
```

<code>4536</code> gènes sont recensés dans le fichier d'annotation.

## Contrôle qualité

Lancez l'outil <strong class="tool">fastqc</strong> @fastqc dédié à l'analyse de la qualité des bases issues d'un séquençage haut-débit

```{bash}
# Changement de répertoire de travail
cd ../quality-controls
# Chargement du module fastqc
module load fastqc
# Lancement des analyses qualités
srun fastqc ../raw-data/SRR10390685_1.fastq -o .
srun fastqc ../raw-data/SRR10390685_2.fastq -o .
# Rapport MultiQC
module load multiqc
srun multiqc -d . -o .
```

La qualité des bases vous paraît-elle satisfaisante ? Pourquoi ?

- [x] Oui
- [ ] Non


car <code>les valeurs de score qualité sont élevées (> Q30)</code> comme le montre <code>le graphique "Per base sequence quality"</code>

Lien vers le [rapport MulitQC](https://github.com/gaellelelandais/DUBii2021/blob/master/multiqc_report.html)

Est-ce que les reads déposés ont subi une étape de nettoyage avant d'être déposés ? Pourquoi ?

- [x] Oui
- [ ] Non

car <code>tous les reads n'ont pas la même longueur</code>

Quelle est la profondeur de séquençage (calculée par rapport à la taille du génome de référence) ?

```{bash}
# Utilisation de la formule du cours :
# N*L/G ; avec N = Nombre de lectures, L = Longueur des lectures et G = Taille du génome 
# ((7066055 * 2) * 151) / 4215606 = 506.2021  
```

La profondeur de séquençage est de : <code>500</code> X.

## Nettoyage des reads

Vous voulez maintenant nettoyer un peu vos lectures. Choisissez les paramètres de <strong class="tool">fastp</strong> @fastp qui vous semblent adéquats et justifiez-les.

```{bash}
# Changement du répertoire de travail
cd ../clean-data
# Chargement du logiciel fastp
module load fastp
# Ressources sur le cluster
salloc --cpus-per-task=10 --mem=5G
# Lancement de fastp
srun fastp --in1 ../raw-data/SRR10390685_1.fastq --in2 ../raw-data/SRR10390685_2.fastq --out1 ./SRR10390685_1_clean.fastq --out2 ./SRR10390685_2_clean.fastq --html ./fastp.html --cut_mean_quality 30 --cut_window_size 8 --length_required 100 --cut_tail --json ./fastp.json
```

Les paramètres suivants ont été choisis : 


|Parametre | Valeur | Explication |
|----------|--------|-------------|
| cut_mean_quality |30  |Valeur utilisée lors de la séance de TP  |
| cut_window_size |8  |Valeur utilisée lors de la séance de TP  |
| length_required |100  |Valeur utilisée lors de la séance de TP  |
| cut_tail |  |Utilisée lors de la séance de TP |

Ces paramètres ont permis de conserver <code>13.554096 M</code> reads pairés, soit une perte de <code>4.1</code>% des reads bruts.

## Alignement des reads sur le génome de référence

Maintenant, vous allez aligner ces reads nettoyés sur le génome de référence à l'aide de <strong class="tool">bwa</strong> @bwa et <strong class="tool">samtools</strong> @samtools.

```{bash}
# Changement de répertoire
cd ../mapping/
# Lancement de BWA
module load bwa
# Création des index
srun bwa index ../raw-data/GCF_000009045.1_ASM904v1_genomic.fna
# Lancement du programme
srun bwa mem ../raw-data/GCF_000009045.1_ASM904v1_genomic.fna ../clean-data/SRR10390685_1_clean.fastq ../clean-data/SRR10390685_2_clean.fastq > SRR10390685.sam
```

Combien de reads ne sont pas mappés ?

```{bash}

```


<code></code> reads ne sont pas mappés.

## Croisement de données

Calculez le nombre de reads qui chevauchent avec au moins 50% de leur longueur le gène _trmNF_ grâce à l'outil <strong class="tool">bedtools</strong> @bedtools:

```{bash}

```

<code> </code> reads chevauchent le gène d'intérêt.


## Visualisation

Utilisez <strong class="tool">IGV</strong> @igv sous [sa version en ligne](https://igv.org/app/) pour visualiser les alignements sur le gène. Faites une capture d'écran du gène entier.

# References